import "modern-normalize/modern-normalize.css";
import "./styles.css";
import finalReviver from "./modules/Reviver";
import Task from "./modules/Task";
import Project from "./modules/Project";
import ToDoList from "./modules/ToDoList";
import { saveList, loadList } from "./modules/Storage";

window.Task = Task;
window.Project = Project;
window.ToDoList = ToDoList;
let testInboxTask1 = new Task('uwu', 'owo', 3, new Date(2026, 3, 5));
let testInboxTask2 = new Task('umu', 'omo', 2, new Date(2026, 3, 6));
testInboxTask2.switchComplete();
let testInboxTask3 = new Task('uku', 'oko', 1, new Date(2026, 3, 7));
let testCustomTask1 = new Task('uyu', 'oyo', 2, new Date(2026, 3, 5));
let testCustomTask2 = new Task('uyu', 'oyo', 3, new Date(2026, 3, 6));
testCustomTask2.switchComplete();
let testProject1 = new Project('usu', 'oso');
let testProject2 = new Project('unu', 'ono');
testProject1.addTask(testCustomTask1);
testProject1.addTask(testCustomTask2);
let testList = new ToDoList();
testList.inbox.addTask(testInboxTask1);
testList.inbox.addTask(testInboxTask2);
testList.inbox.addTask(testInboxTask3);
testList.addProject(testProject1);
testList.addProject(testProject2);
window.testList = testList;
window.reviver = finalReviver;
window.saveList = saveList;
window.loadList = loadList;